image: Visual Studio 2017
version: 1.0.{build}
environment:
  INCLUDE: C:\Program Files\Java\jdk10\include;C:\Program Files\Java\jdk10\include\win32
install:
  - cinst pandoc
  - set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
build_script:
  - call vcvars64.bat
  - nmake /nologo dist
artifacts:
  - path: tolk.zip
    name: Tolk
deploy:
  release: tolk-v$(appveyor_build_version)
  description: 'Tolk screen reader abstraction library'
  provider: GitHub
  auth_token:
    secure: EORyCtVzeWcS+3dDsbyL51W23kE3u7MiRnu91qCYe/TZvs+mGSA44co46sdb5HU2
  artifact: tolk.zip
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true 
